# Generated by Django 4.0.3 on 2022-03-29 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('HOUSEHOLDER', 'Householder'), ('TENANT', 'Tenant')], default='TENANT', max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('profile_pic', models.FileField(default=None, null=True, upload_to='ProfilePics/')),
                ('stripe_acc', models.CharField(max_length=100, null=True)),
                ('profession', models.CharField(max_length=50)),
                ('citizenship', models.FileField(default=None, null=True, upload_to='Citizenships/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Householder',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('Users.user',),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('Users.user',),
        ),
    ]
