# Generated by Django 4.0.2 on 2022-03-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_is_active_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.FileField(default=None, null=True, upload_to='Citizenships/'),
        ),
    ]
