# Generated by Django 4.0.2 on 2022-02-28 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rentAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wasteDisposal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='House.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
