# Generated by Django 4.0.3 on 2022-04-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='electricity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='wasteDisposal',
        ),
        migrations.AddField(
            model_name='bill',
            name='electricityCost',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='wasteDisposalCost',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='waterCost',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rentAmount',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
