# Generated by Django 4.0.3 on 2022-04-14 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bills', '0002_remove_bill_electricity_remove_bill_wastedisposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='householder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='billHouseholder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='billTenant', to=settings.AUTH_USER_MODEL),
        ),
    ]
