# Generated by Django 4.0.3 on 2022-04-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0003_bill_householder_alter_bill_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('DUE', 'Due')], default='DUE', max_length=50),
        ),
    ]
