# Generated by Django 4.0.4 on 2022-06-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bills', '0005_bill_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paymentURL',
            field=models.TextField(null=True),
        ),
    ]
