# Generated by Django 4.0.3 on 2022-03-29 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.FileField(null=True, upload_to='')),
                ('floors', models.IntegerField(null=True)),
                ('rooms', models.IntegerField(null=True)),
                ('monthlyRent', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('HOUSEHOLDER', 'Householder'), ('BOOKED', 'Booked'), ('INACTIVE', 'Inactive')], default='HOUSEHOLDER', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('householder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='householder_fk', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
