# Generated by Django 4.0.2 on 2022-02-28 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.FileField(null=True, upload_to='')),
                ('house_no', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('householder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='householder_fk', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
