# Generated by Django 4.0.3 on 2022-04-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('AVAILAVLE', 'Available'), ('OCCUPIED', 'Occupied'), ('INACTIVE', 'Inactive')], default='AVAILAVLE', max_length=50),
        ),
    ]
