# Generated by Django 4.0.3 on 2022-04-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0003_alter_house_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='floors',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='latitude',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='longitude',
            field=models.FloatField(default=85),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='monthlyRent',
            field=models.DecimalField(decimal_places=5, default=1000, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
