# Generated by Django 4.0.4 on 2022-06-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0004_alter_house_floors_alter_house_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='paymentURL',
            field=models.TextField(null=True),
        ),
    ]
