# Generated by Django 4.0.4 on 2022-06-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0005_house_paymenturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='paymentURL',
        ),
    ]
